import {useRef} from 'react'
import {useGLTF} from '@react-three/drei'
// import { useFrame, useThree } from "@react-three/fiber";
import {animated} from '@react-spring/three'
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import ISLAND_SCENE_GLB from '../assets/3d/island.glb';

type IslandProps = JSX.IntrinsicElements['group'] & {
    isRotating?: boolean
    setIsRotating?: (isRotating: boolean) => void
}

/**
 * Auto-generated by: https://github.com/pmndrs/gltfjsx
 * Author: nimzu (https://sketchfab.com/nimzuk)
 * License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
 * Source: https://sketchfab.com/3d-models/foxs-islands-163b68e09fcc47618450150be7785907
 * Title: Fox's islands
 */
function IslandModel(props: IslandProps) {
    const islandRef = useRef(null)
    const {nodes, materials} = useGLTF(ISLAND_SCENE_GLB)
    return (
        <animated.group ref={islandRef} {...props}>
            <mesh
                geometry={nodes.polySurface944_tree_body_0?.geometry}
                material={materials.PaletteMaterial001}
            />
            <mesh
                geometry={nodes.polySurface945_tree1_0?.geometry}
                material={materials.PaletteMaterial001}
            />
            <mesh
                geometry={nodes.polySurface946_tree2_0?.geometry}
                material={materials.PaletteMaterial001}
            />
            <mesh
                geometry={nodes.polySurface947_tree1_0.geometry}
                material={materials.PaletteMaterial001}
            />
            <mesh
                geometry={nodes.polySurface948_tree_body_0.geometry}
                material={materials.PaletteMaterial001}
            />
            <mesh
                geometry={nodes.polySurface949_tree_body_0.geometry}
                material={materials.PaletteMaterial001}
            />
            <mesh
                geometry={nodes.pCube11_rocks1_0.geometry}
                material={materials.PaletteMaterial001}
            />
        </animated.group>
    )
}

useGLTF.preload(ISLAND_SCENE_GLB)

export default IslandModel
